export const wordsWithMeanings = [
    { word: "about", meaning: "concerning; on the subject of" },
    { word: "account", meaning: "a record of financial transactions" },
    { word: "across", meaning: "from one side to the other" },
    { word: "addition", meaning: "the act of adding something" },
    { word: "after", meaning: "following in time or place" },
    { word: "again", meaning: "once more; another time" },
    { word: "against", meaning: "opposed to; in contact with" },
    { word: "agreement", meaning: "a mutual understanding or contract" },
    { word: "almost", meaning: "nearly; not quite" },
    { word: "among", meaning: "in the middle of; surrounded by" },
    { word: "amount", meaning: "a total quantity" },
    { word: "amusement", meaning: "something entertaining or funny" },
    { word: "angle", meaning: "the space between two meeting lines" },
    { word: "angry", meaning: "feeling strong displeasure" },
    { word: "animal", meaning: "a living creature, not a plant" },
    { word: "answer", meaning: "a reply or solution" },
    { word: "apparatus", meaning: "equipment for a specific task" },
    { word: "apple", meaning: "a round fruit with red or green skin" },
    { word: "approval", meaning: "the act of accepting or agreeing" },
    { word: "argument", meaning: "a reason or a verbal dispute" },
    { word: "attack", meaning: "an aggressive action" },
    { word: "attempt", meaning: "an effort to do something" },
    { word: "attention", meaning: "the act of focusing the mind" },
    { word: "authority", meaning: "the power to give orders" },
    { word: "automatic", meaning: "working by itself" },
    { word: "awake", meaning: "not asleep" },
    { word: "balance", meaning: "a state of stability" },
    { word: "basin", meaning: "a wide, round container" },
    { word: "basket", meaning: "a container woven from materials" },
    { word: "beautiful", meaning: "pleasing to the eye or mind" },
    { word: "because", meaning: "for the reason that" },
    { word: "before", meaning: "earlier in time" },
    { word: "behaviour", meaning: "the way someone acts" },
    { word: "belief", meaning: "an acceptance that something is true" },
    { word: "berry", meaning: "a small, juicy fruit" },
    { word: "between", meaning: "in the space separating two things" },
    { word: "birth", meaning: "the act of being born" },
    { word: "bitter", meaning: "having a sharp, unpleasant taste" },
    { word: "black", meaning: "the darkest colour" },
    { word: "blade", meaning: "the flat, sharp part of a tool or weapon" },
    { word: "blood", meaning: "the red liquid in bodies" },
    { word: "board", meaning: "a flat, thin piece of wood" },
    { word: "boiling", meaning: "very hot; at 100°C for water" },
    { word: "bottle", meaning: "a container with a narrow neck" },
    { word: "brain", meaning: "the organ that controls thoughts" },
    { word: "brake", meaning: "a device to stop movement" },
    { word: "branch", meaning: "a part of a tree that grows from the trunk" },
    { word: "brass", meaning: "a yellow metal mixture" },
    { word: "bread", meaning: "a food made from flour and baked" },
    { word: "breath", meaning: "air taken in or let out of the lungs" },
    { word: "brick", meaning: "a block used for building" },
    { word: "bridge", meaning: "a structure that connects two places" },
    { word: "bright", meaning: "giving a lot of light" },
    { word: "broken", meaning: "damaged; not whole" },
    { word: "brother", meaning: "a male sibling" },
    { word: "brown", meaning: "a colour between red and yellow" },
    { word: "brush", meaning: "a tool with bristles for cleaning" },
    { word: "bucket", meaning: "a round container with a handle" },
    { word: "building", meaning: "a structure with walls and a roof" },
    { word: "burst", meaning: "to break suddenly" },
    { word: "business", meaning: "the activity of trading or working" },
    { word: "butter", meaning: "a yellow food made from milk" },
    { word: "button", meaning: "a small object used to fasten clothes" },
    { word: "camera", meaning: "a device for taking pictures" },
    { word: "canvas", meaning: "a strong cloth used for tents and sails" },
    { word: "carriage", meaning: "a vehicle pulled by horses" },
    { word: "cause", meaning: "a reason for something" },
    { word: "certain", meaning: "sure; without doubt" },
    { word: "chain", meaning: "a series of linked metal rings" },
    { word: "chalk", meaning: "a soft white rock used for writing" },
    { word: "chance", meaning: "an opportunity or possibility" },
    { word: "change", meaning: "to make or become different" },
    { word: "cheap", meaning: "low in price" },
    { word: "cheese", meaning: "a food made from milk curds" },
    { word: "chemical", meaning: "a substance with a specific composition" },
    { word: "chest", meaning: "the front part of the body" },
    { word: "chief", meaning: "the leader of a group" },
    { word: "church", meaning: "a building for Christian worship" },
    { word: "circle", meaning: "a round shape with no corners" },
    { word: "clean", meaning: "free from dirt" },
    { word: "clear", meaning: "easy to see or understand" },
    { word: "clock", meaning: "a device that shows time" },
    { word: "cloth", meaning: "fabric material for making clothes" },
    { word: "cloud", meaning: "a mass of water droplets in the sky" },
    { word: "collar", meaning: "a band around the neck of clothes" },
    { word: "colour", meaning: "the property of objects seen by eyes" },
    { word: "comfort", meaning: "a state of ease and relaxation" },
    { word: "committee", meaning: "a group formed to make decisions" },
    { word: "common", meaning: "usual; shared by many" },
    { word: "company", meaning: "a business organisation" },
    { word: "complete", meaning: "having all parts; finished" },
    { word: "complex", meaning: "made of many parts" },
    { word: "condition", meaning: "the state of something" },
    { word: "conscious", meaning: "aware; awake" },
    { word: "control", meaning: "the power to direct something" },
    { word: "copper", meaning: "a reddish-brown metal" },
    { word: "cotton", meaning: "a soft white fibre from a plant" },
    { word: "cough", meaning: "to force air from the lungs with a sudden sound" },
    { word: "country", meaning: "a nation with its own government" },
    { word: "cover", meaning: "to place something over another to protect or conceal" },
    { word: "crack", meaning: "a narrow break or opening" },
    { word: "credit", meaning: "trust allowing one to obtain goods or services before payment" },
    { word: "crime", meaning: "an act against the law" },
    { word: "cruel", meaning: "showing a lack of kindness or mercy" },
    { word: "crush", meaning: "to press or squeeze with force" },
    { word: "current", meaning: "a flow of water, air, or electricity" },
    { word: "curtain", meaning: "a piece of fabric hung to cover a window or stage" },
    { word: "curve", meaning: "a smoothly bending line or shape" },
    { word: "cushion", meaning: "a soft padded object for sitting or leaning on" },
    { word: "damage", meaning: "harm that reduces value or usefulness" },
    { word: "danger", meaning: "the possibility of harm or injury" },
    { word: "daughter", meaning: "a female child" },
    { word: "death", meaning: "the end of life" },
    { word: "decision", meaning: "a choice made after thinking" },
    { word: "degree", meaning: "a unit of measurement or a level of study" },
    { word: "delicate", meaning: "easily broken or damaged" },
    { word: "dependent", meaning: "relying on someone or something" },
    { word: "design", meaning: "a plan or drawing for something to be made" },
    { word: "desire", meaning: "a strong wish for something" },
    { word: "detail", meaning: "a small part of something larger" },
    { word: "different", meaning: "not the same" },
    { word: "digestion", meaning: "the process of breaking down food in the body" },
    { word: "direction", meaning: "the course along which someone or something moves" },
    { word: "dirty", meaning: "not clean" },
    { word: "discovery", meaning: "finding something for the first time" },
    { word: "disease", meaning: "an illness affecting the body or mind" },
    { word: "disgust", meaning: "a strong feeling of dislike" },
    { word: "distance", meaning: "the space between two points" },
    { word: "division", meaning: "the act of separating into parts" },
    { word: "doubt", meaning: "a feeling of uncertainty" },
    { word: "drain", meaning: "a pipe that carries away waste water" },
    { word: "drawer", meaning: "a box-like storage compartment that slides in and out" },
    { word: "dress", meaning: "a one-piece garment for women or girls" },
    { word: "drink", meaning: "a liquid taken into the body" },
    { word: "driving", meaning: "the act of controlling a vehicle" },
    { word: "early", meaning: "happening before the usual time" },
    { word: "earth", meaning: "the planet we live on" },
    { word: "education", meaning: "the process of learning and teaching" },
    { word: "effect", meaning: "a result or outcome" },
    { word: "elastic", meaning: "able to stretch and return to its original shape" },
    { word: "electric", meaning: "powered by electricity" },
    { word: "engine", meaning: "a machine that converts power into motion" },
    { word: "enough", meaning: "sufficient in quantity or degree" },
    { word: "equal", meaning: "being the same in quantity, size, or value" },
    { word: "error", meaning: "a mistake" },
    { word: "event", meaning: "something that happens" },
    { word: "every", meaning: "including all members of a group" },
    { word: "example", meaning: "a thing that shows what something is like" },
    { word: "exchange", meaning: "the act of giving one thing and receiving another" },
    { word: "existence", meaning: "the state of being alive or real" },
    { word: "expansion", meaning: "the process of becoming larger" },
    { word: "expert", meaning: "a person with special knowledge or skill" },
    { word: "false", meaning: "not true" },
    { word: "family", meaning: "a group of related people" },
    { word: "father", meaning: "a male parent" },
    { word: "feather", meaning: "a light growth on a bird’s body" },
    { word: "feeble", meaning: "weak or lacking strength" },
    { word: "feeling", meaning: "an emotional state" },
    { word: "female", meaning: "of the sex that can bear offspring" },
    { word: "fertile", meaning: "able to produce crops or offspring" },
    { word: "fiction", meaning: "literature that describes imaginary events" },
    { word: "field", meaning: "an area of open land" },
    { word: "fight", meaning: "a violent struggle" },
    { word: "finger", meaning: "one of the five parts at the end of a hand" },
    { word: "first", meaning: "coming before all others" },
    { word: "fixed", meaning: "firmly in place" },
    { word: "flame", meaning: "the visible part of a fire" },
    { word: "flight", meaning: "the act of flying" },
    { word: "floor", meaning: "the surface of a room that you walk on" },
    { word: "flower", meaning: "the coloured part of a plant that produces seeds" },
    { word: "foolish", meaning: "lacking good sense or judgement" },
    { word: "force", meaning: "strength or energy applied to an action" },
    { word: "forward", meaning: "toward a position ahead" },
    { word: "frame", meaning: "a rigid structure that surrounds or supports" },
    { word: "frequent", meaning: "happening often" },
    { word: "friend", meaning: "a person one knows well and trusts" },
    { word: "front", meaning: "the forward-facing part of something" },
    { word: "fruit", meaning: "the part of a plant that contains seeds" },
    { word: "future", meaning: "time that is yet to come" },
    { word: "garden", meaning: "a piece of land used for growing plants" },
    { word: "general", meaning: "affecting or including most people or things" },
    { word: "glass", meaning: "a hard, transparent material" },
    { word: "glove", meaning: "a covering for the hand" },
    { word: "grain", meaning: "small, hard seeds of food plants" },
    { word: "grass", meaning: "green plants with narrow leaves covering the ground" },
    { word: "great", meaning: "very large or important" },
    { word: "green", meaning: "the colour of growing plants" },
    { word: "group", meaning: "a number of people or things together" },
    { word: "growth", meaning: "the process of increasing in size" },
    { word: "guide", meaning: "a person who shows the way" },
    { word: "hammer", meaning: "a tool for hitting nails" },
    { word: "hanging", meaning: "the act of being suspended" },
    { word: "happy", meaning: "feeling pleasure or contentment" },
    { word: "harbour", meaning: "a sheltered place for ships" },
    { word: "harmony", meaning: "a pleasing arrangement of parts" },
    { word: "healthy", meaning: "being well in body and mind" },
    { word: "hearing", meaning: "the ability to perceive sound" },
    { word: "heart", meaning: "the organ that pumps blood through the body" },
    { word: "history", meaning: "the study of past events" },
    { word: "hollow", meaning: "having an empty space inside" },
    { word: "horse", meaning: "a large four-legged animal used for riding or work" },
    { word: "hospital", meaning: "a place where sick or injured people are treated" },
    { word: "house", meaning: "a building for people to live in" },
    { word: "humour", meaning: "the quality of being funny or entertaining" },
    { word: "important", meaning: "of great significance or value" },
    { word: "impulse", meaning: "a sudden strong urge or desire" },
    { word: "increase", meaning: "to become larger in number or amount" },
    { word: "industry", meaning: "economic activity concerned with production of goods" },
    { word: "insect", meaning: "a small creature with six legs and usually wings" },
    { word: "insurance", meaning: "a system of protection against loss or damage" },
    { word: "interest", meaning: "curiosity or concern about something" },
    { word: "invention", meaning: "a new device, method, or process created" },
    { word: "island", meaning: "land surrounded by water" },
    { word: "jelly", meaning: "a soft, sweet food made from fruit juice and sugar" },
    { word: "jewel", meaning: "a precious stone, often used in jewellery" },
    { word: "journey", meaning: "travel from one place to another" },
    { word: "judge", meaning: "a person who decides cases in court" },
    { word: "kettle", meaning: "a container for boiling water" },
    { word: "knife", meaning: "a tool with a blade for cutting" },
    { word: "knowledge", meaning: "information, understanding, or skill gained" },
    { word: "language", meaning: "a system of words used for communication" },
    { word: "laugh", meaning: "to make sounds of amusement" },
    { word: "learning", meaning: "the process of acquiring knowledge" },
    { word: "leather", meaning: "material made from animal skin" },
    { word: "letter", meaning: "a written message sent to someone" },
    { word: "level", meaning: "a flat or equal position or stage" },
    { word: "library", meaning: "a place where books are kept for reading or borrowing" },
    { word: "light", meaning: "something that makes things visible" },
    { word: "limit", meaning: "a point beyond which something cannot go" },
    { word: "linen", meaning: "fabric made from flax" },
    { word: "liquid", meaning: "a substance that flows freely, like water" },
    { word: "little", meaning: "small in size or amount" },
    { word: "living", meaning: "being alive" },
    { word: "loose", meaning: "not firmly fixed or held" },
    { word: "machine", meaning: "a device that performs tasks using power" },
    { word: "manager", meaning: "a person who controls or directs something" },
    { word: "market", meaning: "a place where goods are bought and sold" },
    { word: "married", meaning: "joined in marriage" },
    { word: "match", meaning: "a stick that produces fire when struck" },
    { word: "material", meaning: "the substance from which something is made" },
    { word: "measure", meaning: "to find the size, amount, or degree of something" },
    { word: "medical", meaning: "relating to the treatment of illness" },
    { word: "meeting", meaning: "a gathering of people for discussion" },
    { word: "memory", meaning: "the ability to remember things" },
    { word: "metal", meaning: "a hard, shiny material such as iron or gold" },
    { word: "middle", meaning: "the centre point of something" },
    { word: "military", meaning: "relating to the armed forces" },
    { word: "minute", meaning: "a unit of time equal to 60 seconds" },
    { word: "mixed", meaning: "combining different things" },
    { word: "money", meaning: "a medium of exchange for goods and services" },
    { word: "monkey", meaning: "a small primate with a long tail" },
    { word: "month", meaning: "a period of about 30 days" },
    { word: "morning", meaning: "the early part of the day" },
    { word: "mother", meaning: "a female parent" },
    { word: "motion", meaning: "the act of moving" },
    { word: "mountain", meaning: "a large natural elevation of land" },
    { word: "mouth", meaning: "the opening through which food is taken in" },
    { word: "muscle", meaning: "tissue in the body that produces movement" },
    { word: "music", meaning: "organised sound that expresses emotion or ideas" },
    { word: "narrow", meaning: "not wide" },
    { word: "nation", meaning: "a country and its people" },
    { word: "natural", meaning: "existing in nature, not made by humans" },
    { word: "necessary", meaning: "required or essential" },
    { word: "needle", meaning: "a thin, pointed tool used for sewing" },
    { word: "nerve", meaning: "a fibre that carries signals in the body" },
    { word: "night", meaning: "the time between sunset and sunrise" },
    { word: "noise", meaning: "unwanted or unpleasant sound" },
    { word: "normal", meaning: "usual or expected" },
    { word: "north", meaning: "one of the four main compass directions" },
    { word: "number", meaning: "a symbol representing a quantity" },
    { word: "offer", meaning: "to present something for acceptance" },
    { word: "office", meaning: "a place where work is done, often at desks" },
    { word: "operation", meaning: "a medical procedure or an organised activity" },
    { word: "opinion", meaning: "a personal belief or view" },
    { word: "opposite", meaning: "completely different or facing across" },
    { word: "orange", meaning: "a round fruit with a thick orange skin" },
    { word: "order", meaning: "an instruction or arrangement" },
    { word: "ornament", meaning: "a decoration" },
    { word: "other", meaning: "different from the one mentioned" },
    { word: "owner", meaning: "a person who possesses something" },
    { word: "paint", meaning: "a coloured substance applied to surfaces" },
    { word: "paper", meaning: "material for writing or printing on" },
    { word: "parallel", meaning: "lines or surfaces that run side by side and never meet" },
    { word: "parcel", meaning: "a package or bundle" },
    { word: "paste", meaning: "a thick, soft substance" },
    { word: "payment", meaning: "the act of giving money for goods or services" },
    { word: "peace", meaning: "a state of calm and absence of conflict" },
    { word: "pencil", meaning: "a tool for writing or drawing" },
    { word: "person", meaning: "a human being" },
    { word: "physical", meaning: "relating to the body" },
    { word: "picture", meaning: "a visual representation" },
    { word: "place", meaning: "a particular location" },
    { word: "plane", meaning: "a flat surface or an aircraft" },
    { word: "plant", meaning: "a living organism that grows in soil" },
    { word: "plate", meaning: "a flat dish for food" },
    { word: "please", meaning: "to cause satisfaction or happiness" },
    { word: "pleasure", meaning: "a feeling of enjoyment" },
    { word: "plough", meaning: "a tool used for turning over soil in farming" },
    { word: "pocket", meaning: "a small pouch sewn into clothing" },
    { word: "point", meaning: "a particular spot or position" },
    { word: "poison", meaning: "a substance that can cause harm or death" },
    { word: "polish", meaning: "to make something smooth and shiny" },
    { word: "political", meaning: "relating to government or public affairs" },
    { word: "porter", meaning: "a person who carries luggage" },
    { word: "position", meaning: "the place where something is located" },
    { word: "possible", meaning: "able to be done or achieved" },
    { word: "potato", meaning: "a starchy root vegetable" },
    { word: "powder", meaning: "a dry substance made of fine particles" },
    { word: "power", meaning: "the ability to do or control something" },
    { word: "present", meaning: "a gift, or happening now" },
    { word: "price", meaning: "the amount of money something costs" },
    { word: "print", meaning: "to produce text or images on paper" },
    { word: "prison", meaning: "a place where criminals are kept" },
    { word: "private", meaning: "belonging to one person, not public" },
    { word: "probable", meaning: "likely to happen" },
    { word: "process", meaning: "a series of steps to achieve something" },
    { word: "produce", meaning: "to create or make something" },
    { word: "profit", meaning: "money gained from business after costs" },
    { word: "property", meaning: "something owned by someone" },
    { word: "prose", meaning: "ordinary written or spoken language" },
    { word: "protest", meaning: "an expression of objection or disapproval" },
    { word: "public", meaning: "open or available to everyone" },
    { word: "purpose", meaning: "the reason for doing something" },
    { word: "quality", meaning: "the standard or level of something" },
    { word: "question", meaning: "a sentence that asks for information" },
    { word: "quick", meaning: "moving fast" },
    { word: "quiet", meaning: "making little or no noise" },
    { word: "quite", meaning: "to a certain or significant extent" },
    { word: "range", meaning: "the limits between which something varies" },
    { word: "reaction", meaning: "a response to something" },
    { word: "reading", meaning: "the act of looking at and understanding written words" },
    { word: "ready", meaning: "prepared for something" },
    { word: "reason", meaning: "a cause or explanation" },
    { word: "receipt", meaning: "a written proof of payment" },
    { word: "record", meaning: "to write down or store information" },
    { word: "regret", meaning: "a feeling of sadness about something past" },
    { word: "regular", meaning: "happening at fixed times or intervals" },
    { word: "relation", meaning: "a connection between people or things" },
    { word: "religion", meaning: "a system of faith or worship" },
    { word: "request", meaning: "an act of asking politely for something" },
    { word: "respect", meaning: "admiration or regard for someone" },
    { word: "reward", meaning: "something given in return for effort" },
    { word: "rhythm", meaning: "a repeated pattern of sound or movement" },
    { word: "right", meaning: "morally good, or a legal entitlement" },
    { word: "river", meaning: "a large natural stream of water" },
    { word: "rough", meaning: "having an uneven surface" },
    { word: "round", meaning: "shaped like a circle or ball" },
    { word: "scale", meaning: "a set of levels, or a device for weighing" },
    { word: "school", meaning: "a place where children are educated" },
    { word: "science", meaning: "the study of the natural world" },
    { word: "scissors", meaning: "a tool for cutting paper or cloth" },
    { word: "screw", meaning: "a metal fastener with a spiral groove" },
    { word: "second", meaning: "a unit of time, or the one after first" },
    { word: "secret", meaning: "something kept hidden" },
    { word: "secretary", meaning: "a person who handles office tasks" },
    { word: "selection", meaning: "the act of choosing" },
    { word: "sense", meaning: "a natural ability like sight or hearing" },
    { word: "separate", meaning: "to divide into parts" },
    { word: "serious", meaning: "important and not funny" },
    { word: "servant", meaning: "a person employed to work in a household" },
    { word: "shade", meaning: "an area sheltered from direct sunlight" },
    { word: "shake", meaning: "to move back and forth quickly" },
    { word: "shame", meaning: "a painful feeling of guilt or embarrassment" },
    { word: "sharp", meaning: "having a thin edge that can cut" },
    { word: "sheep", meaning: "a farm animal with woolly coat" },
    { word: "shelf", meaning: "a flat surface for holding things" },
    { word: "shirt", meaning: "a piece of clothing for the upper body" },
    { word: "shock", meaning: "a sudden upsetting or surprising event" },
    { word: "short", meaning: "not long in length" },
    { word: "silver", meaning: "a shiny, grey-white precious metal" },
    { word: "simple", meaning: "easy to understand" },
    { word: "sister", meaning: "a female sibling" },
    { word: "skirt", meaning: "a piece of clothing worn from the waist down" },
    { word: "sleep", meaning: "a natural state of rest for the body and mind" },
    { word: "slope", meaning: "a surface that slants up or down" },
    { word: "small", meaning: "not large in size" },
    { word: "smash", meaning: "to break into pieces with force" },
    { word: "smell", meaning: "the sense of detecting odours" },
    { word: "smile", meaning: "a facial expression showing happiness" },
    { word: "smoke", meaning: "the visible gas from burning" },
    { word: "smooth", meaning: "having an even surface" },
    { word: "snake", meaning: "a long, legless reptile" },
    { word: "sneeze", meaning: "to suddenly blow air through the nose" },
    { word: "society", meaning: "a community of people living together" },
    { word: "solid", meaning: "firm and not liquid or gas" },
    { word: "sound", meaning: "something that can be heard" },
    { word: "south", meaning: "one of the four main compass directions" },
    { word: "space", meaning: "the area beyond Earth, or an empty area" },
    { word: "spade", meaning: "a tool for digging" },
    { word: "special", meaning: "different from others, important" },
    { word: "sponge", meaning: "a soft material that absorbs liquid" },
    { word: "spoon", meaning: "a utensil used for eating or stirring" },
    { word: "spring", meaning: "a season, or a coiled piece of metal" },
    { word: "square", meaning: "a shape with four equal sides" },
    { word: "stage", meaning: "a raised platform for performances" },
    { word: "stamp", meaning: "a small paper mark used for postage" },
    { word: "start", meaning: "the beginning of something" },
    { word: "statement", meaning: "a clear expression in words" },
    { word: "station", meaning: "a place where trains or buses stop" },
    { word: "steam", meaning: "Water in the form of vapour" },
    { word: "steel", meaning: "Strong metal made from iron" },
    { word: "stick", meaning: "Thin piece of wood" },
    { word: "sticky", meaning: "Something that easily adheres" },
    { word: "stiff", meaning: "Not flexible or hard to bend" },
    { word: "still", meaning: "Not moving or silent" },
    { word: "stitch", meaning: "Loop of thread in sewing" },
    { word: "stocking", meaning: "Long sock worn on the leg" },
    { word: "stomach", meaning: "Part of the body where food is digested" },
    { word: "stone", meaning: "Hard, solid mineral material" },
    { word: "store", meaning: "Place where goods are sold" },
    { word: "story", meaning: "Account of events, real or imagined" },
    { word: "straight", meaning: "Without bend or curve" },
    { word: "strange", meaning: "Unfamiliar or unusual" },
    { word: "street", meaning: "Public road in a city or town" },
    { word: "stretch", meaning: "To extend or make longer" },
    { word: "strong", meaning: "Having great power or force" },
    { word: "structure", meaning: "Arrangement of parts in a whole" },
    { word: "substance", meaning: "Physical material of something" },
    { word: "sudden", meaning: "Happening quickly and unexpectedly" },
    { word: "sugar", meaning: "Sweet substance used in food" },
    { word: "summer", meaning: "Warmest season of the year" },
    { word: "support", meaning: "To hold up or give help" },
    { word: "surprise", meaning: "Something unexpected" },
    { word: "sweet", meaning: "Sugary in taste" },
    { word: "system", meaning: "Set of connected parts working together" },
    { word: "table", meaning: "Piece of furniture with a flat top" },
    { word: "taste", meaning: "Flavour experienced in the mouth" },
    { word: "teaching", meaning: "Act of educating or instructing" },
    { word: "tendency", meaning: "An inclination or habit" },
    { word: "theory", meaning: "Idea explaining something" },
    { word: "there", meaning: "In that place" },
    { word: "thick", meaning: "Wide from one side to the other" },
    { word: "thing", meaning: "An object or matter" },
    { word: "thought", meaning: "Idea or mental process" },
    { word: "thread", meaning: "Fine string for sewing" },
    { word: "throat", meaning: "Front part of the neck" },
    { word: "through", meaning: "From one side to another" },
    { word: "thumb", meaning: "Short, thick finger" },
    { word: "thunder", meaning: "Loud sound after lightning" },
    { word: "ticket", meaning: "Pass showing payment or entry" },
    { word: "tight", meaning: "Firm and difficult to move" },
    { word: "tired", meaning: "Feeling in need of rest" },
    { word: "together", meaning: "With each other" },
    { word: "tomorrow", meaning: "Day after today" },
    { word: "tongue", meaning: "Organ in the mouth for taste and speech" },
    { word: "tooth", meaning: "Hard structure in the mouth for biting" },
    { word: "touch", meaning: "To make physical contact" },
    { word: "trade", meaning: "Exchange of goods or services" },
    { word: "train", meaning: "Series of railway carriages" },
    { word: "transport", meaning: "Movement of people or goods" },
    { word: "trick", meaning: "Clever act to deceive" },
    { word: "trouble", meaning: "Difficulty or problem" },
    { word: "trousers", meaning: "Clothing for the legs" },
    { word: "twist", meaning: "To turn or bend something" },
    { word: "umbrella", meaning: "Device for protection from rain" },
    { word: "under", meaning: "Below something" },
    { word: "value", meaning: "Worth or importance" },
    { word: "verse", meaning: "Line of poetry" },
    { word: "vessel", meaning: "Container or ship" },
    { word: "violent", meaning: "Using force to harm" },
    { word: "voice", meaning: "Sound made when speaking" },
    { word: "waiting", meaning: "Staying until something happens" },
    { word: "waste", meaning: "Unwanted material or misuse" },
    { word: "watch", meaning: "Small timepiece for the wrist" },
    { word: "water", meaning: "Clear liquid essential for life" },
    { word: "weather", meaning: "Condition of the atmosphere" },
    { word: "weight", meaning: "Measure of heaviness" },
    { word: "wheel", meaning: "Circular object that rotates" },
    { word: "where", meaning: "At what place" },
    { word: "while", meaning: "Period of time" },
    { word: "whistle", meaning: "High-pitched blowing sound" },
    { word: "white", meaning: "Colour of snow or milk" },
    { word: "window", meaning: "Opening in a wall with glass" },
    { word: "winter", meaning: "Coldest season of the year" },
    { word: "woman", meaning: "Adult female human" },
    { word: "wound", meaning: "Injury to the body" },
    { word: "writing", meaning: "Act of forming words on a surface" },
    { word: "wrong", meaning: "Not correct" },
    { word: "yellow", meaning: "Colour of the sun" },
    { word: "yesterday", meaning: "Day before today" },
    { word: "young", meaning: "Not old; early in life" }
]
